spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:https://avparcialconfigserver.azurewebsites.net

#eureka:
#  instance:
#    hostname: avcatalogservice.azurewebsites.net