server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
