eureka:
  client:
    service-url:
      defaultZone: https://avparcialeurekaserver.azurewebsites.net/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 

info:
  author: Ronilson Alves
  mail: falecom@ronilsonalves.com
server:
  port: ${PORT:8091}
message: Configurações Genéricas

spring:
  cloud:
    ineutils:
      timeout-seconds: 10
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: trace
